import re, pywikibot, datetime, time, bz2, sys
from pywikibot import xmlreader
from pywikibot import textlib
from bz2 import BZ2File


xmlversion = '20190201'

#http://stackoverflow.com/questions/500864/case-insensitive-python-regular-expression-without-re-compile

print(datetime.datetime.now())

xmlfile = '{lang}wiki-{ver}-pages-articles.xml'.format(lang='lv',ver=xmlversion)
file_to_save = '{lang} - typolist [{ver}].txt'.format(lang='lv',ver=xmlversion)

file = open(file_to_save, "w", encoding='utf-8')

normallist_old = [
	#'nģ',
	#'anģ[eē]',
	'enģe(?!rmāņ)',
	#'aps',#laikapstākļi, apsegi, apstrādāts
	################'pa\s(laikam|retam|visam)',
	'kaut(kas|kād|kur|kad)',
	'sazin(kas|kād|kur|kad)',
	'diez(kas|kād|kur|kad)',
	'diezin(kas|kād|kur|kad)',
	'nez(kas|kād|kur|kad)',
	'nezin(kas|kād|kur|kad)',
	'kolon(?!āde|ij)',
	#'iej',
	'europ(?!e)',##############URL - daudz
	#'meš',
	'pirms\sKr(istus)?\.?\s',
	#'viss\s(\w{4,})',
	'U(\d{2,})',
	'tāpēc\skad',
	't(ā|ur|ik)\spat',
	####'līd?z\s?ko',
	'\blīdz\sko\b','\blīz\s?ko\b',
	#'dzīvesgājum',
	'it(in)?(kā|ne)\s?(kāds|kas|kur|maz|viens)',
	'(auto)?mobīl',
	#'sekojoši', - ir otrā skriptā
	'gūlb',
	'trenner',
	'pēctam',
	'inscin',
	'ganjau',
	'fosīl',
	'ģērbo',#'apģērbos'
	'albūm',
	'tekstīl',
	'higēn',
	'(m|d)(agnet|ikt|ikr)afon',
	'patalo[ģg]',
	'stabīl',
	#'Āfrikā', - jebkurā gadījumā jāapvieno ar nākamo
	#'āfrikā',
	###'licen[zžs](?!\s*=)',
	'dzelzbet',
	'tēmek',
	'patreiz',
	#####'t[aā]p[eē]c',
	'tāpec','tap[eē]c',
	'pie\s[tk]am',
	'nummur(?!muiž)',
	'kantrī\s(\w)',###apvienot ar nākamo?
	'kantrī',
	'debate\b',
	'acīm\sredz(ot|am)',
	'(tur)?pretīm',
	'konditorij',
	####'lok[ao]m[ao]tī',
	'lokomatī','lokam[ao]tī',
	'gērbo',
	'ekanomi',
	'dakān',
	'luksafor',
	'\bpar\scik\b',
	'tolet',
	####'m[aā]jas\s?lap(?!a\s*=)',
	'mājas\slap(?!a\s*=)','majas\s?lap(?!a\s*=)',
	'viduskol',
	#####################'i[sz]+tab',
	##'š[kķ]i[ņn][ķk]',
	#################'šķi[ņn][ķk]','š[kķ]i[ņn][ķk]',
	's[kķ]i[ņn][ķk]',
	###'dzel[zs]*ceļ',
	'dzelceļ','dzelzsceļ'
	'rengen',
	'modēm',
	'datu\sbāzes',
	'datu\s?bāžu',
	'datubāzu\svadība(\w*)',
	##'ŗ',
	'entuazism',
	'intres',
	'patreizēj',
	'vislaik',
	'[nt](u|ā|e|ik|ur)patās',
	'[ct]ikārt',
	'otreiz',
	'tiko',
	'\ba(iz|r)\svien\b',
	###'hip[\s-]?hop',
	'hip[\s-]hop',
	'klavi[ae]tūr',
	'propogand',
	'kontroband',
	'orandž',
	####'t[aā]d[ēe]j[āa]di',
	'tādej[āa]di','tad[ēe]j[āa]di','t[āa]dējadi',###########visi varianti?
	###'bat[ae]r[ie]j',
	'baterej','batar[ie]j',
	#'du[bp]lik[aā]t',
	'duplik[aā]t','dublikat',
	'kompoten',
	'helihopter',
	'\besu\b',
	'atvilkn',
	#'inž[ie]n(ie|ē)r',
	'inženēr','inžin(ie|ē)r',
	'mitaloģi',
	'paralimp',
	'jo\sprojām',
	'hi[ea]rhi',
	#'t[aā]l[āa]k',
	'tālak','tal[āa]k',
	'laima\sslimīb',
	'fīl',
	#'ļe[nņ][ķk]',
	'[lļ]eņk','[lļ]en[ķk]',
	'sīnus(?<!tok|ap)',
	'tēlotāja\smākslā',
	'gardrob',
	'orģināl',
	#########look behind fix
	'tezaur',
	######################################################'tezaur(?<!https?://[\w\.\,\;\:\/\?\&\%\+\=\-\#\~\!\(\)\*_]+)',
	
	#'dzied[aā]t[aā]j',
	'(?<!ap)dziedātaj','dziedat[aā]j',
	'fotogrāfē',
	#'\bvi[ņn][šs]\b',
	'\bviņs\b','\bvin[šs]\b',
	#'\bvi[ņn]a\b',
	'\bvina\b',
	'atēl',
	'plastalīn',
	'noziedzinie',
	'želantīn',
	#'že[nņ][sš]e[nņ]',
	###########################uzlabot    'žeņ[sš]en','že[nņ]šeņ','že[nņ][sš]e[nņ]',
	'šederv',
	'ornoment',
	'kalei?d[ao]skop',
	'atkreditācij',
	'°K',
	'netikai',
	#'sav+aļ+',
	#'sav+an+',
	'žandr',
	'asteorīd',
	'savlaicīgi',
	#'nosta[ļl][ģg]i',
	'ekspidīcij',
	'department',
	#'uni?versi?tāt',
	#'p\.?m\?.e\.*',
	#'p\.?m\?.e\.?',
	'pasual',
	'\bne\skā\b',
	'Los\sAndželos',
	#'al[hk][ao]kol',
	####jāpieliek XML failā izmaiņa hols -> [kh]ols
	##alkohols - pareizi
	'alh[ao][hk]ol','alka[hk]ol',###########varbūt ir vēl varianti
	'katreiz',
	'arhitip',
	'\baneks(?!i)',
	'dienasta',
	'anegdot',
	'caumur',
	#########'sp[eē]l[eē]t[aā]j',
	'venēr',
	'ananās',
	'kreiv',
	'vice-(\w|č)',
	'anti-(\w)',
	'eks-(\w)',
	#'<[\/\\]?(hr|br)( [^\/\\>]+?)? ?[\/\\]?>',
	#############?????   'aneks',
	#'kā, piemēram',
	#'kā piemēram',
	#'\{\{[Cc]ommons\|[Cc]ategory\:',
	'merikaņu',
	#'<div class="references-small"><references /></div>',
	#'<div class="references-small"> <references /> </div>',
	#'<references />',
	#'\{\{[Vv]al-',
	#'vjl\.',
	#'vjl',
	#'uc\.',
	#'uc',
	#'u\.t\.t\.\.',
	#'u\.t\.t\.',
	#'m2\(\?!\\s\*=\)',
	'\bārī\b',
	'mēdij',
	'patreiz',
	'aplikācij',
	#'(\d)\.?\-(tiem|tie|tajos|tos|to|tajiem)',
	'\d\.?-?t?a?j?(iem?|os?)',
	'ēbrej',
	'\bairod',
	'lakus efekt',
	#'([A-Za-zĀČĒĢĪĶĻŅŠŪŽāčēģīķļņšūž]+)\s+\1',
	#'enģe',
	#'eanģ', ????????????
	#'<!-- Bota izveidots nosaukums -->',
	#'v[eē]l[āa]k',
	'vēlak','vel[āa]k',
	'pēdējaj',
	'jugendstil',
	'tāllekšan',
	'diplomat(?!ique|ic)',
	'sokrāt',
	'sālskāb',
	'organizāt',
	'pantēr',
	'officiāl',
	'atiecīb',
	'arh[eo]lo',
	'relfej',
	'funci',
	'tirznie',
	'atrak','ātrak','atrāk',#atrak: pam'atrak'sts
	'San Francisko',
	#'Rio\s?[Dd]e\s?[Žž]aneiro',
	#'Sankt[\s-]?[Pp][eē]terburga',
	'pār lieku',
	'uguns dzēšanas aparāt',
	'lūgtim',
	'merkaķ',
	'topagr[aā]f',
	'\Balo(ģg)',
	'kakadū',
	'\bši\b',
	'džente?lmeni?',
	'kompilāt',
	'interpretāt',
	'vērā ņemam',
	'sutin',
	'arandžē',
	'džemper(?!i)',
	'privili',
	#'di[aeo]c[eē][zs]',
	'venezu',
	'gh?ett?o(?!games)',
	'harizm',
	'marazm',
	'karnivāl',
	'balzām',
	'islam',
	'ekumēn',
	'ezotēr',
	'Bergām',
	'psihodēl',
	'metere?o',
	'\Bātor\B',
	#'bibli?ot[eē]k',
	'holēr',
	'jurispuden',
	'skult[uū]r',
	'trenkrakst',
	'precenden',
	'fila[sz]of',
	'pulve[dž]',
	'Mičigān',
	'gēl(?!(iski|u valod))',
	'tornad',
	'adiabat',
	'aprec',
	'finansu',
	'karat[iu]',
	'magnet(?!iz|osf|ic)',
	'karniv',
	'parono',
	'dinazaur',
	'kapell',
	'Nujork',
	'vēsnie',
	'milij(on|ar)',
	#'foll?ij',
	#'foll?ijs',
	'galvanai',
	'tasmāni',
	'hermofrod',
	'kuņg','kunģ',
	'r[ie]ģip',
	'hābsb',
	'temp(re|er)tūr',
	'normāņ',
	'dermantī[tn]',
	'intrav',
	'olīve',
	'zolīd',
	'vakum',
	'\bto starp\b',
	#######'koler',
	'amērik',
	'visuāl',
	'raksnie',
	'Sanmarino',
	###'izc[īi]n[īi]',
	'diagram\B(?!m)',
	'intre',
	'arhetek',
	'grizli l',
	'litert',
	'rešis',
	#'art ?[Dd]e[ck]o',
	####otrajā sarakstā
	'priek[šs]ēdēt',
	'recedīv',
	'debeskr',
	'Monāko',
	'apsolv',
	'moldāvieš'
]

normallist22222 = [
	#'nģ',
	#'anģ[eē]',
	'enģe(?!rmāņ)',
	#'aps',#laikapstākļi, apsegi, apstrādāts
	'pa\s(laikam|retam|visam)',
	'kaut(kas|kād|kur|kad)',
	'sazin(kas|kād|kur|kad)',
	'diez(kas|kād|kur|kad)',
	'diezin(kas|kād|kur|kad)',
	'nez(kas|kād|kur|kad)',
	'nezin(kas|kād|kur|kad)',
	'kolon(?!āde|i|n)',
	'iej',
	#####'europ(?!e)',##############URL - daudz
	'meš',
	'pirms\sKr(istus)?\.?\s',
	#'viss\s(\w{4,})',
	####################pielabot vajag 'U(\d{2,})',
	'\btāpēc\skad\b',
	'\bt(ā|ur|ik)\spat\b',
	####'līd?z\s?ko',
	'līdz\sko','līz\s?ko',
	#'dzīvesgājum',
	'it(in)?(kā|ne)\s?(kāds|kas|kur|maz|viens)',
	'(auto)?mobīl',
	#'sekojoši', - ir otrā skriptā
	'gūlb',
	'trenner',
	'pēctam',
	'inscin',
	'ganjau',
	'fosīl',
	'ģērbo',#'apģērbos'
	'albūm',
	'tekstīl',
	'higēn',
	'(m|d)(agnet|ikt|ikr)afon',
	'patalo[ģg]',
	'stabīl',
	'Āfrikā',
	'āfrikā',
	'licen[zžs](?!\s*=)',
	'dzelzbet',
	'tēmek',
	'patreiz',
	#####'t[aā]p[eē]c',
	'tāpec','tap[eē]c',
	'pie\s[tk]am\b',
	'nummur(?!muiž)',
	'kantrī\s(\w)',###apvienot ar nākamo?
	'kantrī',
	'debate\b',
	'acīm\sredz(ot|am)',
	'\b(tur)?pretīm',#daudz 'iepretīm'
	'konditorij',
	####'lok[ao]m[ao]tī',
	'lokomatī','lokam[ao]tī',
	'gērbo',
	'ekanomi',
	'dakān',
	'luksafor',
	'par\scik',
	'tolet',
	####'m[aā]jas\s?lap(?!a\s*=)',
	'mājas\slap(?!a\s*=)','majas\s?lap(?!a\s*=)',
	'viduskol',
	'i[sz]+tab',
	##'š[kķ]i[ņn][ķk]',
	#################'šķi[ņn][ķk]','š[kķ]i[ņn][ķk]',
	's[kķ]i[ņn][ķk]',
	###'dzel[zs]*ceļ',
	'dzelceļ','dzelzsceļ'
	'rengen',
	'modēm',
	'datu\sbāzes',
	'datu\s?bāžu',
	'datubāzu\svadība(\w*)',
	'ŗ',
	'entuazism',
	'intres',
	'patreizēj',
	'vislaik',
	'[nt](u|ā|e|ik|ur)patās',
	'[ct]ikārt',
	'otreiz',
	'\btiko\b',
	'\ba(iz|r)\svien\b',
	###'hip[\s-]?hop',
	'hip[\s-]hop',
	'klavi[ae]tūr',
	'propogand',
	'kontroband',
	'orandž',
	####'t[aā]d[ēe]j[āa]di',
	'tādej[āa]di','tad[ēe]j[āa]di','t[āa]dējadi',###########visi varianti?
	###'bat[ae]r[ie]j',
	'baterej','batar[ie]j',
	#'du[bp]lik[aā]t',
	'duplik[aā]t','dublikat',
	'kompoten',
	'helihopter',
	'\besu\b',
	'atvilkn',
	#'inž[ie]n(ie|ē)r',
	'inženēr','inžin(ie|ē)r',
	'mitaloģi',
	'paralimp',
	'jo\sprojām',
	'hi[ea]rhi',
	#'t[aā]l[āa]k',
	'tālak','tal[āa]k',
	'laima\sslimīb',
	##############'fīl',
	#'ļe[nņ][ķk]',
	###################'[lļ]eņk','[lļ]en[ķk]',
	'sīnus',
	'tēlotāja\smākslā',
	'gardrob',
	'orģināl',
	#########look behind fix
	'tezaur',
	######################################################'tezaur(?<!https?://[\w\.\,\;\:\/\?\&\%\+\=\-\#\~\!\(\)\*_]+)',
	
	#'dzied[aā]t[aā]j',
	'dziedātaj','dziedat[aā]j',
	'fotogrāfē',
	#'\bvi[ņn][šs]\b',
	'\bviņs\b','\bvin[šs]\b',
	#'\bvi[ņn]a\b',
	'\bvina\b',
	'(?<!fil)atēl',
	'plastalīn',
	'noziedzinie',
	'želantīn',
	#'že[nņ][sš]e[nņ]',
	###########################uzlabot    'žeņ[sš]en','že[nņ]šeņ','že[nņ][sš]e[nņ]',
	'šederv',
	'ornoment',
	'kalei?d[ao]skop',
	'atkreditācij',
	'°K',
	'netikai',
	#'sav+aļ+',
	#'sav+an+',
	'žandr',
	'asteorīd',
	'savlaicīgi',
	#'nosta[ļl][ģg]i',
	'ekspidīcij',
	'department\B',
	#'uni?versi?tāt',
	#'p\.?m\?.e\.*',
	#'p\.?m\?.e\.?',
	'pasual',
	'ne\skā',
	'Los\sAndželos',
	#'al[hk][ao]kol',
	####jāpieliek XML failā izmaiņa hols -> [kh]ols
	##alkohols - pareizi
	'alh[ao][hk]ol','alka[hk]ol',###########varbūt ir vēl varianti
	'katreiz',
	'arhitip',
	'aneks(?!i)',
	'dienasta(?!uriņ)',
	'anegdot',
	'caumur',
	#########'sp[eē]l[eē]t[aā]j',
	'venēr',
	'ananās',
	'kreiv',
	'\bvice-(\w|č)',
	'\banti-(\w)',
	'\beks-(\w)',
	#'<[\/\\]?(hr|br)( [^\/\\>]+?)? ?[\/\\]?>',
	'aneks',
	'kā, piemēram',
	'kā piemēram',
	#'\{\{[Cc]ommons\|[Cc]ategory\:',
	'merikaņu',
	#'<div class="references-small"><references /></div>',
	#'<div class="references-small"> <references /> </div>',
	#'<references />',
	#'\{\{[Vv]al-',
	#'vjl\.',
	#'vjl',
	#'uc\.',
	#'uc',
	#'u\.t\.t\.\.',
	#'u\.t\.t\.',
	#'m2\(\?!\\s\*=\)',
	'\bārī\b',
	'\bmēdij',
	'patreiz',
	'aplikācij',
	#'(\d)\.?\-(tiem|tie|tajos|tos|to|tajiem)',
	###############uzlabot '\d\.?-?t?a?j?(iem?|os?)',
	'ēbrej',
	'airod',
	'lakus efekt',
	#'([A-Za-zĀČĒĢĪĶĻŅŠŪŽāčēģīķļņšūž]+)\s+\1',
	#'enģe',
	#'eanģ', ????????????
	#'<!-- Bota izveidots nosaukums -->',
	#'v[eē]l[āa]k',
	'vēlak','vel[āa]k',
	'pēdējaj',
	'jugendstil',
	'tāllekšan',
	'diplomat(?!ique)',
	'sokrāt',
	'sālskāb',
	'organizāt',
	'pantēr',
	'officiāl',
	'atiecīb',
	'arh[eo]lo',
	'relfej',
	'funci',
	'tirznie',
	'(?<!pam)atrak(?!st)','ātrak','atrāk',#atrak: pam'atrak'sts
	'San Francisko',
	#'Rio\s?[Dd]e\s?[Žž]aneiro',
	#'Sankt[\s-]?[Pp][eē]terburga',
	'pār lieku',
	'uguns dzēšanas aparāt',
	'lūgtim',
	'merkaķ',
	'topagr[aā]f',
	'\Balo(ģg)',
	'kakadū',
	'\bši\b',
	'džente?lmeni?',
	'kompilāt',
	'interpretāt',
	'vērā ņemam',
	'sutin',
	'arandžē',
	'džemper(?!i)',
	'privili',
	#'di[aeo]c[eē][zs]',
	'venezu(?!el)',
	###########'gh?ett?o(?!\sgames)',
	'harizm',
	'marazm',
	'karnivāl',
	'balzām',
	##############'islam',
	'ekumēn',
	'ezotēr',
	'Bergām',
	'psihodēl',
	'metere?o',
	'\Bātor\B',
	#'bibli?ot[eē]k',
	'holēr',
	'jurispuden',
	'skult[uū]r',
	'trenkrakst',
	'precenden',
	'fila[sz]of',
	'pulve[dž]',
	'Mičigān',
	'gēl(?!(iski|u valod))',
	'tornad',
	'adiabat',
	'aprec',
	'finansu',
	'karat[iu]',
	'magnet(?!iz)',
	'karniv',
	'parono',
	'dinazaur',
	'kapell(?!i|o)',
	'Nujork',
	'vēsnie',
	'milij(on|ar)',
	#'foll?ij',
	#'foll?ijs',
	'galvanai',
	'tasmāni',
	'hermofrod',
	'kuņg','kunģ',
	'r[ie]ģip',
	'hābsb',
	'temp(re|er)tūr',
	'normāņ',
	'dermantī[tn]',
	'intrav',
	'olīve',
	'zolīd',
	'vakum',
	'to starp',
	'koler',
	'amērik',
	'visuāl',
	'raksnie',
	'Sanmarino',
	###'izc[īi]n[īi]',
	'diagram(?!m)',
	'intre',
	'arhetek',
	'grizli l',
	'litert',
	'rešis',
	#'art ?[Dd]e[ck]o',
	####otrajā sarakstā
	'priek[šs]ēdēt',
	'recedīv',
	'debeskr',
	'Monāko',
	'apsolv',
	'moldāvieš'
]

normallist = [
	#'nģ',
	#'anģ[eē]',
	'enģe(?!rmāņ)',
	#'aps',#laikapstākļi, apsegi, apstrādāts
	###############'pa\s(laikam|retam|visam)',
	'kaut(kas|kād|kur|kad)',
	'sazin(kas|kād|kur|kad)',
	'diez(kas|kād|kur|kad)',
	'diezin(kas|kād|kur|kad)',
	'nez(kas|kād|kur|kad)',
	'nezin(kas|kād|kur|kad)',
	'kolon(?!āde|i|n)',
	#'iej',
	#####'europ(?!e)',##############URL - daudz
	#'meš',
	'pirms\sKr(istus)?\.?\s',
	#'viss\s(\w{4,})',
	####################pielabot vajag 'U(\d{2,})',
	'\btāpēc\skad\b',
	'\bt(ā|ur|ik)\spat\b',
	####'līd?z\s?ko',
	'līdz\sko','līz\s?ko',
	#'dzīvesgājum',
	'it(in)?(kā|ne)\s?(kāds|kas|kur|maz|viens)',
	'(auto)?mobīl',
	#'sekojoši', - ir otrā skriptā
	'gūlb',
	'trenner',
	'pēctam',
	'inscin',
	'ganjau',
	'fosīl',
	'ģērbo',#'apģērbos'
	'albūm',
	'tekstīl',
	'higēn',
	'(m|d)(agnet|ikt|ikr)afon',
	'patalo[ģg]',
	'stabīl', 
	#'Āfrikā', - jebkurā gadījumā jāapvieno ar nākamo
	#'āfrikā',
	####'licen[zžs](?!\s*=)',
	'dzelzbet',
	'tēmek',
	'patreiz',
	#####'t[aā]p[eē]c',
	'tāpec','tap[eē]c',
	'pie\s[tk]am\b',
	'nummur(?!muiž)',
	####'kantrī\s(\w)',###apvienot ar nākamo?
	'kantrī',
	'debate\b',
	'acīm\sredz(ot|am)',
	'\b(tur)?pretīm',#daudz 'iepretīm'
	'konditorij',
	####'lok[ao]m[ao]tī',
	'lokomatī','lokam[ao]tī',
	'gērbo',
	'ekanomi',
	'dakān',
	'luksafor',
	'par\scik',
	'tolet',
	####'m[aā]jas\s?lap(?!a\s*=)',
	'mājas\slap(?!a\s*=)','majas\s?lap(?!a\s*=)',
	'viduskol',
	#######'i[sz]+tab',
	##'š[kķ]i[ņn][ķk]',
	#################'šķi[ņn][ķk]','š[kķ]i[ņn][ķk]',
	's[kķ]i[ņn][ķk]',
	###'dzel[zs]*ceļ',
	'dzelceļ','dzelzsceļ'
	'rengen',
	'modēm',
	'datu\sbāzes',
	'datu\s?bāžu',
	'datubāzu\svadība(\w*)',
	#######'ŗ',
	'entuazism',
	'intres',
	'patreizēj',
	'vislaik',
	'[nt](u|ā|e|ik|ur)patās',
	'[ct]ikārt',
	'otreiz',
	'\btiko\b',
	'\ba(iz|r)\svien\b',
	###'hip[\s-]?hop',
	'hip[\s-]hop',
	'klavi[ae]tūr',
	'propogand',
	'kontroband',
	'orandž',
	####'t[aā]d[ēe]j[āa]di',
	'tādej[āa]di','tad[ēe]j[āa]di','t[āa]dējadi',###########visi varianti?
	###'bat[ae]r[ie]j',
	'baterej','batar[ie]j',
	#'du[bp]lik[aā]t',
	'duplik[aā]t','dublikat',
	'kompoten',
	'helihopter',
	'\besu\b',
	'atvilkn',
	#'inž[ie]n(ie|ē)r',
	'inženēr','inžin(ie|ē)r',
	'mitaloģi',
	'paralimp',
	'jo\sprojām',
	'hi[ea]rhi',
	#'t[aā]l[āa]k',
	'tālak','tal[āa]k',
	'laima\sslimīb',
	##############'fīl',
	#'ļe[nņ][ķk]',
	###################'[lļ]eņk','[lļ]en[ķk]',
	'sīnus(?<!tok)(?<!apel)',
	'tēlotāja\smākslā',
	'gardrob',
	'orģināl',
	#########look behind fix
	###'tezaur',
	######################################################'tezaur(?<!https?://[\w\.\,\;\:\/\?\&\%\+\=\-\#\~\!\(\)\*_]+)',

	#'dzied[aā]t[aā]j',
	'(?<!ap)dziedātaj','dziedat[aā]j',
	'fotogrāfē',
	#'\bvi[ņn][šs]\b',
	'\bviņs\b','\bvin[šs]\b',
	#'\bvi[ņn]a\b',
	'\bvina\b',
	'(?<!fil)atēl',
	'plastalīn',
	'noziedzinie',
	'želantīn',
	#'že[nņ][sš]e[nņ]',
	###########################uzlabot    'žeņ[sš]en','že[nņ]šeņ','že[nņ][sš]e[nņ]',
	'šederv',
	'ornoment',
	'kalei?d[ao]skop',
	'atkreditācij',
	'°K',
	'netikai',
	#'sav+aļ+',
	#'sav+an+',
	'žandr',
	'asteorīd',
	'savlaicīgi',
	#'nosta[ļl][ģg]i',
	'ekspidīcij',
	'department\B',
	#'uni?versi?tāt',
	#'p\.?m\?.e\.*',
	#'p\.?m\?.e\.?',
	'pasual',
	'\bne\skā\b',
	'Los\sAndželos',
	#'al[hk][ao]kol',
	####jāpieliek XML failā izmaiņa hols -> [kh]ols
	##alkohols - pareizi
	'alh[ao][hk]ol','alka[hk]ol',###########varbūt ir vēl varianti
	'katreiz',
	'arhitip',
	'aneks(?!i)',
	'dienasta(?!uriņ)',
	'anegdot',
	'caumur',
	#########'sp[eē]l[eē]t[aā]j',
	'venēr',
	'ananās',
	'kreiv',
	'\bvice-(\w|č)',
	'\banti-(\w)',
	'\beks-(\w)',
	#'<[\/\\]?(hr|br)( [^\/\\>]+?)? ?[\/\\]?>',
	######'aneks',
	#'kā, piemēram',
	#'kā piemēram',
	#'\{\{[Cc]ommons\|[Cc]ategory\:',
	'merikaņu',
	#'<div class="references-small"><references /></div>',
	#'<div class="references-small"> <references /> </div>',
	#'<references />',
	#'\{\{[Vv]al-',
	#'vjl\.',
	#'vjl',
	#'uc\.',
	#'uc',
	#'u\.t\.t\.\.',
	#'u\.t\.t\.',
	#'m2\(\?!\\s\*=\)',
	'\bārī\b',
	'\bmēdij',
	'patreiz',
	'aplikācij',
	#'(\d)\.?\-(tiem|tie|tajos|tos|to|tajiem)',
	###############uzlabot '\d\.?-?t?a?j?(iem?|os?)',
	'ēbrej',
	'\bairod',
	'lakus efekt',
	#'([A-Za-zĀČĒĢĪĶĻŅŠŪŽāčēģīķļņšūž]+)\s+\1',
	#'enģe',
	#'eanģ', ????????????
	#'<!-- Bota izveidots nosaukums -->',
	#'v[eē]l[āa]k',
	'vēlak','vel[āa]k',
	'pēdējaj',
	'jugendstil',
	'tāllekšan',
	'diplomat(?!ique)',
	'sokrāt',
	'sālskāb',
	'organizāt',
	'pantēr',
	'officiāl',
	'atiecīb',
	'arh[eo]lo',
	'relfej',
	'funci',
	'tirznie',
	'(?<!pam)atrak(?!st)','ātrak','atrāk',#atrak: pam'atrak'sts
	'San Francisko',
	#'Rio\s?[Dd]e\s?[Žž]aneiro',
	#'Sankt[\s-]?[Pp][eē]terburga',
	'pār lieku',
	'uguns dzēšanas aparāt',
	'lūgtim',
	'merkaķ',
	'topagr[aā]f',
	'\Balo(ģg)',
	'kakadū',
	'\bši\b',
	'džente?lmeni?',
	'kompilāt',
	'interpretāt',
	'vērā ņemam',
	'sutin',
	'arandžē',
	'džemper(?!i)',
	'privili',
	#'di[aeo]c[eē][zs]',
	'venezu(?!el)',
	###########'gh?ett?o(?!\sgames)',
	'harizm',
	'marazm',
	'karnivāl',
	'balzām',
	##############'islam',
	'ekumēn',
	'ezotēr',
	'Bergām',
	'psihodēl',
	'metere?o',
	'\Bātor\B',
	#'bibli?ot[eē]k',
	'holēr',
	'jurispuden',
	'skult[uū]r',
	'trenkrakst',
	'precenden',
	'fila[sz]of',
	'pulve[dž]',
	'Mičigān',
	'gēl(?!(iski|u valod))',
	'tornad',
	'adiabat',
	'aprec',
	'finansu',
	'karat[iu]',
	'magnet(?!iz|osf|ic)',
	'karniv',
	'parono',
	'dinazaur',
	'kapell(?!i|o)',
	'Nujork',
	'vēsnie',
	'milij(on|ar)',
	#'foll?ij',
	#'foll?ijs',
	'galvanai',
	'tasmāni',
	'hermofrod',
	'kuņg','kunģ',
	'r[ie]ģip',
	'hābsb',
	'temp(re|er)tūr',
	'normāņ',
	'dermantī[tn]',
	'intrav',
	'olīve',
	'zolīd',
	'vakum',
	'\bto starp\b',
	###'koler',
	'amērik',
	'visuāl',
	'raksnie',
	'Sanmarino',
	###'izc[īi]n[īi]',
	'diagram(?!m)',
	'intre',
	'arhetek',
	'grizli l',
	'litert',
	'rešis',
	#'art ?[Dd]e[ck]o',
	####otrajā sarakstā
	'priek[šs]ēdēt',
	'recedīv',
	'debeskr',
	'Monāko',
	'apsolv',
	'moldāvieš'
]

checklist = [re.compile(f,re.IGNORECASE) for f in normallist]
#pywikibot.output(checklist[:25])


#, re.IGNORECASE

num = 0

context = 30

numprint = 75

finds = []

start = time.time()

#f = bz2.open('/mnt/nfs/dumps-labstore1006.wikimedia.org/xmldatadumps/public/lvwiki/20180620/lvwiki-20180620-pages-articles.xml.bz2', 'r')
'''
with bz2.BZ2File('/mnt/nfs/dumps-labstore1006.wikimedia.org/xmldatadumps/public/lvwiki/20180620/lvwiki-20180620-pages-articles.xml.bz2') as xml_file:
	for page in xmlreader.XmlDump(xml_file).parse():
		if page.ns == "0" and not page.isredirect:
			pagetext = textlib.unescape(page.text)
			pagetitle = page.title
			
			if num==1000:
				break
			
			num += 1
			if num % numprint == 0:
				print(num)
			
			for checkR in checklist:
				m = checkR.finditer(pagetext)
				if m:
					for found in m:
						sectionname = '<nowiki>'+pagetext[max(0, found.start() - context):found.start()]+'</nowiki><span style="background-color:#fdd;padding:2px;margin:1px">\'\'\''+pagetext[found.start():found.end()]+'\'\'\'</span><nowiki>'+pagetext[found.end() : found.end() + context] + '</nowiki>'
						sectionname = sectionname.replace('\n',' ')
						sectionname = re.sub('\s\s*',' ',sectionname)
						
						finds.append([pagetitle,checkR,sectionname])
					
file.write(str(finds))
end = time.time()
print('Took {} seconds to complete'.format(end-start))
'''

num = 0

context = 30

numprint = 150

finds = []

start = time.time()

paths = '/public/dumps/public/lvwiki/20190201/lvwiki-20190201-pages-articles.xml.bz2'

with BZ2File(paths) as xml_file:
	blah = False
	for page in xmlreader.XmlDump(paths).parse():
		if page.ns == "0" and not page.isredirect:
			pagetext = textlib.unescape(page.text)
			pagetitle = page.title
            
			#if num==100:
			#	break
			
			num += 1
			if num % numprint == 0:
				print(num)
				sys.stdout.flush()
		
			for checkR in checklist:
				m = checkR.finditer(pagetext)
				if m:
					for found in m:
						sectionname = [pagetext[max(0, found.start() - context):found.start()],
						pagetext[found.start():found.end()],
						pagetext[found.end() : found.end() + context]
                        ]#'<nowiki>'+pagetext[max(0, found.start() - context):found.start()]+'</nowiki><span style="background-color:#fdd;padding:2px;margin:1px">\'\'\''+pagetext[found.start():found.end()]+'\'\'\'</span><nowiki>'+pagetext[found.end() : found.end() + context] + '</nowiki>'
						#sectionname = sectionname.replace('\n',' ')
                        
						#sectionname = re.sub('\s\s*',' ',sectionname)
						blah = True
						finds.append([pagetitle,checkR,sectionname])
					
file.write(str(finds))
end = time.time()
print('Took {} seconds to complete'.format(end-start))
file.close()